name: engagement_env_mac
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py312hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - bleak==2.1.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - hsluv==5.0.4
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mne==1.11.0
      - mne-lsl==1.12.0
      - numpy==2.4.1
      - openmuse==0.1.8
      - pandas==3.0.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - psutil==7.2.1
      - pylsl==1.18.1
      - pynput==1.8.1
      - pyobjc-core==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-corebluetooth==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-libdispatch==12.1
      - pyobjc-framework-quartz==12.1
      - pyparsing==3.3.2
      - pyqtgraph==0.14.0
      - python-dateutil==2.9.0.post0
      - pyxdf==1.17.3
      - qtpy==2.4.3
      - requests==2.32.5
      - scipy==1.17.0
      - six==1.17.0
      - tqdm==4.67.1
      - urllib3==2.6.3
      - vispy==0.16.1
prefix: /opt/anaconda3/envs/engagement_env_mac
